/**
 * AUTO-GENERATED by scripts/seed-intros.ts. Do not edit by hand — re-run
 * the script to refresh. The merge in src/content/topics/index.ts reads
 * this map and prepends each entry to its lesson's exercises array.
 */

import type { CuratedExercise } from '../content/types'

export type LessonIntroMap = Record<string, Record<string, CuratedExercise>>
export const LESSON_INTROS: LessonIntroMap = {
  "l7-m-prism-formulas": {
    "connecting-area-and-prism": {
      "kind": "curated",
      "id": "intro-connecting-area-and-prism",
      "difficulty": "intro",
      "instance": {
        "prompt": "A circle has a diameter of $14\\text{ cm}$. Find its circumference, using $\\pi = \\dfrac{22}{7}$. Give your answer in cm.",
        "answer": "44",
        "answerType": "numeric",
        "solution": [
          "The radius is half the diameter, so $r = 14 \\div 2 = 7\\text{ cm}$.",
          "Using $C = 2\\pi r$, we get $C = 2 \\times \\dfrac{22}{7} \\times 7 = 44\\text{ cm}$."
        ],
        "hint": "Circumference is $\\pi$ times the diameter, or $2\\pi$ times the radius."
      }
    }
  },
  "l7-m-triangle-angle-sum": {
    "angle-sums-other-shapes": {
      "kind": "curated",
      "id": "intro-angle-sums-other-shapes",
      "difficulty": "intro",
      "instance": {
        "prompt": "What is the interior angle sum of a pentagon (in degrees)?",
        "answer": "540",
        "answerType": "numeric",
        "solution": [
          "A pentagon has $n = 5$ sides, so use the formula $(n - 2) \\times 180°$.",
          "Substituting gives $(5 - 2) \\times 180° = 3 \\times 180° = 540°$."
        ],
        "hint": "Use $(n - 2) \\times 180°$ with $n = 5$."
      }
    }
  },
  "l7-m-modelling-ratios": {
    "ratio-areas-volumes": {
      "kind": "curated",
      "id": "intro-ratio-areas-volumes",
      "difficulty": "intro",
      "instance": {
        "prompt": "A small shape has area 5 cm². A similar shape is enlarged by linear scale factor $k = 3$. What is its new area (in cm²)?",
        "answer": "45",
        "answerType": "numeric",
        "solution": [
          "Areas scale by $k^2$, so the new area is $3^2 \\times 5 = 9 \\times 5 = 45$ cm²."
        ],
        "hint": "Areas scale by $k^2$."
      }
    }
  },
  "l10a-aa-linear-rational": {
    "simplifying-rational": {
      "kind": "curated",
      "id": "intro-simplifying-rational",
      "difficulty": "intro",
      "instance": {
        "prompt": "Simplify $\\dfrac{1}{4}(8x - 12) + \\dfrac{1}{3}(6x + 9)$. Type the polynomial.",
        "answer": "4x+0",
        "answerType": "polynomial",
        "solution": [
          "Expand the first bracket: $\\dfrac{1}{4}(8x - 12) = 2x - 3$.",
          "Expand the second bracket: $\\dfrac{1}{3}(6x + 9) = 2x + 3$.",
          "Add the results: $2x - 3 + 2x + 3 = 4x$."
        ],
        "hint": "Expand each bracket first, then combine like terms."
      }
    }
  },
  "l10a-aa-factorising-quadratics": {
    "solving-applied": {
      "kind": "curated",
      "id": "intro-solving-applied",
      "difficulty": "intro",
      "instance": {
        "prompt": "Consider the function $f(x) = 3x^2 - 5x + 2$.\n\n(a) Find the $y$-intercept of $f$.\n\n(b) Hence determine the $x$-value(s) where $f(x) = 2$.",
        "answer": "2; 0, 5/3",
        "answerType": "set",
        "solution": [
          "Evaluate $f(0) = 3(0)^2 - 5(0) + 2 = 2$, so the $y$-intercept is $2$.",
          "Set $3x^2 - 5x + 2 = 2$, giving $3x^2 - 5x = 0$.",
          "Factor: $x(3x - 5) = 0$, so $x = 0$ or $x = \\frac{5}{3}$."
        ],
        "hint": "For part (b), try substituting the $y$-intercept value back into $f(x) = 2$."
      }
    }
  }
}
