/**
 * AUTO-GENERATED by scripts/seed-intros.ts. Do not edit by hand — re-run
 * the script to refresh. The merge in src/content/topics/index.ts reads
 * this map and prepends each entry to its lesson's exercises array.
 */

import type { CuratedExercise } from '../content/types'

export type LessonIntroMap = Record<string, Record<string, CuratedExercise>>
export const LESSON_INTROS: LessonIntroMap = {
  "functions-relations": {
    "domain-range": {
      "kind": "curated",
      "id": "intro-domain-range",
      "difficulty": "intro",
      "instance": {
        "prompt": "Find the maximal domain of $f(x) = \\sqrt{x - 3}$. State the answer in the form $[a, \\infty)$. What is the value of $a$?",
        "answer": "3",
        "answerType": "numeric",
        "solution": [
          "The expression under the square root must be non-negative, so $x - 3 \\geq 0$.",
          "This gives $x \\geq 3$, so the maximal domain is $[3, \\infty)$.",
          "Therefore $a = 3$."
        ],
        "hint": "The value inside the square root cannot be negative."
      }
    }
  },
  "linear-quadratic": {
    "quadratic-forms": {
      "kind": "curated",
      "id": "intro-quadratic-forms",
      "difficulty": "intro",
      "instance": {
        "prompt": "What are the coordinates of the turning point of $y = (x - 4)^2 + 3$?",
        "answer": "(4,3)",
        "answerType": "exact",
        "solution": [
          "Compare $y = (x - 4)^2 + 3$ with $y = (x - h)^2 + k$.",
          "Then $h = 4$ and $k = 3$.",
          "The turning point is $(4, 3)$."
        ],
        "hint": "Turning-point form is $(x-h)^2 + k$; here $x-4 = x-h$."
      }
    },
    "completing-square": {
      "kind": "curated",
      "id": "intro-completing-square",
      "difficulty": "intro",
      "instance": {
        "prompt": "For $f(x) = x^2 - 6x + 2$, write $f(x)$ in the form $(x - p)^2 + k$. State the single integer value of $p$.",
        "answer": "3",
        "answerType": "numeric",
        "solution": [
          "Half the coefficient of $x$: $\\frac{-6}{2} = -3$, so $p = 3$.",
          "The turning point occurs at $x = 3$."
        ],
        "hint": "Take half the coefficient of $x$ in $x^2 - 6x + 2$."
      }
    },
    "quadratic-formula": {
      "kind": "curated",
      "id": "intro-quadratic-formula",
      "difficulty": "intro",
      "instance": {
        "prompt": "Compute $\\Delta = b^2 - 4ac$ for $2x^2 - 4x + 2 = 0$. State as an integer.",
        "answer": "0",
        "answerType": "numeric",
        "solution": [
          "Identify $a = 2$, $b = -4$, $c = 2$.",
          "Substitute into the discriminant: $\\Delta = (-4)^2 - 4(2)(2) = 16 - 16 = 0$."
        ],
        "hint": "a = 2, b = -4, c = 2."
      }
    }
  },
  "cubic-quartic": {
    "remainder-factor": {
      "kind": "curated",
      "id": "intro-remainder-factor",
      "difficulty": "intro",
      "instance": {
        "prompt": "Find the remainder when $P(x) = x^3 - 2x^2 + 3x - 7$ is divided by $(x - 2)$.",
        "answer": "3",
        "answerType": "numeric",
        "solution": [
          "By the remainder theorem, the remainder equals $P(2)$.",
          "$P(2) = (2)^3 - 2(2)^2 + 3(2) - 7 = 8 - 8 + 6 - 7 = -1$.",
          "So the remainder is $-1$."
        ],
        "hint": "Evaluate $P(2)$ using the remainder theorem."
      }
    },
    "null-factor-solve": {
      "kind": "curated",
      "id": "intro-null-factor-solve",
      "difficulty": "intro",
      "instance": {
        "prompt": "How many distinct x-intercepts does $y = x(x - 2)(x + 5)$ have?",
        "answer": "3",
        "answerType": "numeric",
        "solution": [
          "The factors are $x$, $(x-2)$ and $(x+5)$.",
          "The distinct roots are $x = 0$, $x = 2$ and $x = -5$.",
          "So there are 3 distinct x-intercepts."
        ],
        "hint": "Each different linear factor gives a separate intercept."
      }
    }
  },
  "transformations-plane": {
    "families-rules": {
      "kind": "curated",
      "id": "intro-families-rules",
      "difficulty": "intro",
      "instance": {
        "prompt": "A line of the form $y = mx + c$ passes through the point $(0, 5)$ and has gradient $m = -2$. Find the value of $c$.",
        "answer": "5",
        "answerType": "numeric",
        "solution": [
          "Substitute the point $(0, 5)$ into $y = mx + c$ to get $5 = (-2)(0) + c$.",
          "Simplify to $5 = c$, so $c = 5$."
        ]
      }
    }
  },
  "simultaneous-equations": {
    "substitution": {
      "kind": "curated",
      "id": "intro-substitution",
      "difficulty": "intro",
      "instance": {
        "prompt": "Solve the system $y = x + 3$ and $x + y = 11$. What is the value of $x$?",
        "answer": "4",
        "answerType": "numeric",
        "solution": [
          "Substitute $y = x + 3$ into $x + y = 11$ to get $x + (x + 3) = 11$.",
          "Simplify to $2x + 3 = 11$, then $2x = 8$, giving $x = 4$."
        ],
        "hint": "Substitute $y = x + 3$ into the second equation."
      }
    }
  },
  "counting": {
    "to-probability": {
      "kind": "curated",
      "id": "intro-to-probability",
      "difficulty": "intro",
      "instance": {
        "prompt": "A committee of 3 people is chosen at random from 5 men and 4 women. Find the probability that the committee contains exactly 2 men. Give as a fraction a/b in simplest form.",
        "answer": "10/21",
        "answerType": "numeric",
        "solution": [
          "Favourable outcomes: $\\binom{5}{2}\\binom{4}{1} = 10 \\cdot 4 = 40$.",
          "Total outcomes: $\\binom{9}{3} = 84$.",
          "Probability = $\\dfrac{40}{84} = \\dfrac{10}{21}$."
        ],
        "hint": "Pick 2 men from 5 and 1 woman from 4 for favourable outcomes; pick any 3 from 9 for total."
      }
    }
  },
  "periodic-properties": {
    "symmetry": {
      "kind": "curated",
      "id": "intro-symmetry",
      "difficulty": "intro",
      "instance": {
        "prompt": "Use the complementary relation $\\sin(\\pi/2 - x) = \\cos x$ to evaluate $\\sin(\\pi/12)$. Give your answer in the form \"sqrt(a)/b\" or \"(sqrt(a)+b)/c\" or \"(sqrt(a)-b)/c\".",
        "answer": "(sqrt(6)-sqrt(2))/4",
        "answerType": "exact",
        "solution": [
          "$\\pi/12 = \\pi/2 - 5\\pi/12$, so $\\sin(\\pi/12) = \\sin(\\pi/2 - 5\\pi/12) = \\cos(5\\pi/12)$. Using $\\cos(5\\pi/12) = \\cos(75°) = (\\sqrt{6} - \\sqrt{2})/4$."
        ],
        "hint": "Express $\\pi/12$ as $\\pi/2 - 5\\pi/12$."
      }
    },
    "modelling": {
      "kind": "curated",
      "id": "intro-modelling",
      "difficulty": "intro",
      "instance": {
        "prompt": "A quantity obeys $y = 5\\cos(x) + 2$. Find its maximum value.",
        "answer": "7",
        "answerType": "numeric",
        "solution": [
          "The amplitude is $|a| = 5$ and the mean value is $c = 2$.",
          "The maximum value of $\\cos(x)$ is $1$, so the maximum of $y$ is $5 \\cdot 1 + 2 = 7$."
        ],
        "hint": "Maximum of $a\\cos(x) + c$ is $c + a$ (for $a > 0$)."
      }
    }
  },
  "logarithms": {
    "log-laws": {
      "kind": "curated",
      "id": "intro-log-laws",
      "difficulty": "intro",
      "instance": {
        "prompt": "Simplify $\\log_a(7) + \\log_a(3)$. Express your answer as $\\log_a(k)$.",
        "answer": "log_a(21)",
        "answerType": "exact",
        "solution": [
          "Using the product law, $\\log_a(7) + \\log_a(3) = \\log_a(7 \\times 3) = \\log_a(21)$."
        ],
        "hint": "Product law: $\\log_a(m) + \\log_a(n) = \\log_a(mn)$."
      }
    }
  },
  "solving-transcendental": {
    "solving-trig": {
      "kind": "curated",
      "id": "intro-solving-trig",
      "difficulty": "intro",
      "instance": {
        "prompt": "Consider the function $f(x) = \\sin(2x) - \\cos(x)$ defined on the interval $[0, 2\\pi]$. Find the smallest positive value of $x$ in $[0, 2\\pi]$ where $f(x) = 0$. Give your answer as a decimal rounded to three decimal places.",
        "answer": "0.000",
        "answerType": "numeric",
        "solution": [
          "Set $f(x) = \\sin(2x) - \\cos(x) = 0$ and use $\\sin(2x) = 2\\sin(x)\\cos(x)$ to get $2\\sin(x)\\cos(x) - \\cos(x) = 0$.",
          "Factor out $\\cos(x)$: $\\cos(x)(2\\sin(x) - 1) = 0$.",
          "Either $\\cos(x) = 0$, giving $x = \\pi/2$ and $x = 3\\pi/2$, or $\\sin(x) = 1/2$, giving $x = \\pi/6$ and $x = 5\\pi/6$.",
          "The smallest positive solution in $[0, 2\\pi]$ is $x = \\pi/6 \\approx 0.524$."
        ],
        "hint": "Rewrite $\\sin(2x)$ using the double-angle identity and factor."
      }
    }
  },
  "newtons-method": {
    "idea": {
      "kind": "curated",
      "id": "intro-idea",
      "difficulty": "intro",
      "instance": {
        "prompt": "Let $f(x) = x^3 - 2x - 5$. Starting with $x_0 = 2$, compute $x_1$ using one step of Newton's method. Give your answer as a decimal to 2 decimal places.",
        "answer": "2.10",
        "answerType": "numeric",
        "solution": [
          "$f(x) = x^3 - 2x - 5$ gives $f(2) = 8 - 4 - 5 = -1$.",
          "$f'(x) = 3x^2 - 2$ gives $f'(2) = 12 - 2 = 10$.",
          "Apply Newton's formula: $x_1 = x_0 - \\dfrac{f(x_0)}{f'(x_0)} = 2 - \\dfrac{-1}{10} = 2.1$.",
          "So $x_1 = 2.10$ (to 2 decimal places)."
        ],
        "hint": "Use $x_{n+1} = x_n - \\dfrac{f(x_n)}{f'(x_n)}$ and compute both $f(2)$ and $f'(2)$ first."
      }
    },
    "one-iteration": {
      "kind": "curated",
      "id": "intro-one-iteration",
      "difficulty": "intro",
      "instance": {
        "prompt": "Apply one Newton step to $f(x) = x^2 - 4$ with $x_0 = 3$. What is $x_1$? Give to 2 dp.",
        "answer": "2.17",
        "answerType": "numeric",
        "solution": [
          "$f(3) = 9 - 4 = 5$ and $f\\prime(3) = 6$.",
          "$x_1 = 3 - 5/6 = 3 - 0.833 = 2.17$ (to 2 dp)."
        ],
        "hint": "Start by evaluating $f(3)$ and $f\\prime(3) = 2x$."
      }
    },
    "refine-cubic": {
      "kind": "curated",
      "id": "intro-refine-cubic",
      "difficulty": "intro",
      "instance": {
        "prompt": "Apply one step of Newton's method to $f(x) = x^3 - 6x + 2$ starting from $x_0 = 0$. Give the value of $x_1$, correct to three decimal places.",
        "answer": "0.333",
        "answerType": "numeric",
        "solution": [
          "Newton's method uses $x_{n+1} = x_n - \\dfrac{f(x_n)}{f'(x_n)}$ with $f'(x) = 3x^2 - 6$.",
          "At $x_0 = 0$: $f(0) = 2$ and $f'(0) = -6$, so $x_1 = 0 - \\dfrac{2}{-6} = \\dfrac{1}{3}$.",
          "Rounded to three decimal places, $x_1 \\approx 0.333$."
        ]
      }
    }
  },
  "differentiation": {
    "stationary-points": {
      "kind": "curated",
      "id": "intro-stationary-points",
      "difficulty": "intro",
      "instance": {
        "prompt": "The graph of a function $f$ has a stationary point at $x = 3$ where $f''(3) < 0$. What type of stationary point is it? Answer \"local maximum\", \"local minimum\", or \"point of inflection\".",
        "answer": "local maximum",
        "answerType": "exact",
        "solution": [
          "At a stationary point, concave down indicates a local maximum."
        ],
        "hint": "Negative second derivative means concave down."
      }
    },
    "motion-graphs": {
      "kind": "curated",
      "id": "intro-motion-graphs",
      "difficulty": "intro",
      "instance": {
        "prompt": "An object moves along a straight line with position $s(t) = t^2 - 4t + 1$, where $s$ is in metres and $t$ is in seconds. Find the time $t$ at which the object is momentarily at rest (i.e. its velocity is zero). Give your answer in seconds.",
        "answer": "2",
        "answerType": "numeric",
        "solution": [
          "Velocity is the derivative of position: $v(t) = s\\prime(t) = 2t - 4$.",
          "Set velocity equal to zero: $2t - 4 = 0$, giving $t = 2$.",
          "So the object is momentarily at rest at $t = 2$ seconds."
        ],
        "hint": "The object is momentarily at rest when its velocity, the derivative of $s(t)$, equals zero."
      }
    },
    "inflection": {
      "kind": "curated",
      "id": "intro-inflection",
      "difficulty": "intro",
      "instance": {
        "prompt": "For $f(x) = x^3 - 3x$, state the $x$-value of the point of inflection.",
        "answer": "0",
        "answerType": "numeric",
        "solution": [
          "Compute $f'(x) = 3x^2 - 3$, then $f''(x) = 6x$. Set $f''(x) = 0$ to get $x = 0$, which is the point of inflection."
        ],
        "hint": "Find where $f''(x) = 6x$ equals zero."
      }
    }
  },
  "antidifferentiation": {
    "families": {
      "kind": "curated",
      "id": "intro-families",
      "difficulty": "intro",
      "instance": {
        "prompt": "Consider the family of curves $f(x) = \\sin(x) + C$. How many members does this family have? Answer \"one\" or \"infinitely many\".",
        "answer": "infinitely many",
        "answerType": "exact",
        "solution": [
          "Since $C$ can be any real number, the family contains infinitely many curves."
        ],
        "hint": "C is free to take any real value."
      }
    },
    "recover-function": {
      "kind": "curated",
      "id": "intro-recover-function",
      "difficulty": "intro",
      "instance": {
        "prompt": "A particle has velocity $v(t) = 6t - 4$ and initial displacement $s(1) = 3$. Find $s(t)$.",
        "answer": "3t^2-4t+4",
        "answerType": "polynomial",
        "solution": [
          "Antidifferentiate: $\\int (6t - 4)\\, dt = 3t^2 - 4t + C$.",
          "Apply $s(1) = 3$: $3(1)^2 - 4(1) + C = 3$, so $C = 4$.",
          "Therefore $s(t) = 3t^2 - 4t + 4$."
        ],
        "hint": "Integrate the velocity, then use the boundary condition to find $C$."
      }
    }
  },
  "probability-compound": {
    "addition-rule": {
      "kind": "curated",
      "id": "intro-addition-rule",
      "difficulty": "intro",
      "instance": {
        "prompt": "For $\\Pr(A) = 0.3$, $\\Pr(B) = 0.6$, $\\Pr(A \\cap B) = 0.1$, find $\\Pr(A \\cup B)$.",
        "answer": "0.8",
        "answerType": "numeric",
        "solution": [
          "Apply the addition rule: $\\Pr(A \\cup B) = \\Pr(A) + \\Pr(B) - \\Pr(A \\cap B)$.",
          "Substitute the values: $\\Pr(A \\cup B) = 0.3 + 0.6 - 0.1 = 0.8$."
        ],
        "hint": "Use the addition rule for compound events."
      }
    },
    "tree-diagrams": {
      "kind": "curated",
      "id": "intro-tree-diagrams",
      "difficulty": "intro",
      "instance": {
        "prompt": "A bag contains $3$ red balls and $2$ blue balls. Two balls are drawn one after the other without replacement. What is the probability that both balls drawn are red? Answer as a fraction.",
        "answer": "3/10",
        "answerType": "numeric",
        "solution": [
          "The probability the first ball is red is $3/5$, and after removing one red ball there are $2$ red and $2$ blue balls left, so the probability the second is red is $2/4 = 1/2$.",
          "Multiplying along the branches of the tree diagram gives $\\Pr(\\text{both red}) = 3/5 \\cdot 1/2 = 3/10$."
        ],
        "hint": "Use a tree diagram with two branches for each draw, and multiply along the path where both draws are red."
      }
    }
  },
  "conditional-probability": {
    "conditional": {
      "kind": "curated",
      "id": "intro-conditional",
      "difficulty": "intro",
      "instance": {
        "prompt": "A bag contains 5 red balls and 3 blue balls. Two balls are drawn **with replacement**. What is $\\Pr(\\text{second is red} \\mid \\text{first is red})$?",
        "answer": "5/8",
        "answerType": "numeric",
        "solution": [
          "Since the events are independent, $\\Pr(\\text{second is red} \\mid \\text{first is red}) = \\Pr(\\text{red}) = 5/8$."
        ],
        "hint": "With replacement, the second draw is independent of the first."
      }
    },
    "independence": {
      "kind": "curated",
      "id": "intro-independence",
      "difficulty": "intro",
      "instance": {
        "prompt": "Two events $A$ and $B$ are independent with $\\Pr(A) = 0.4$ and $\\Pr(B) = 0.5$. Find $\\Pr(A \\cap B)$.",
        "answer": "0.2",
        "answerType": "numeric",
        "solution": [
          "For independent events, $\\Pr(A \\cap B) = \\Pr(A) \\Pr(B)$.",
          "Substituting: $\\Pr(A \\cap B) = 0.4 \\times 0.5 = 0.2$."
        ],
        "hint": "Multiply the two probabilities together."
      }
    }
  },
  "m10-algebra-quadratics": {
    "completing-square": {
      "kind": "curated",
      "id": "intro-completing-square",
      "difficulty": "intro",
      "instance": {
        "prompt": "Solve $x^2 + 6x + 8 = 0$ by completing the square. State the larger root first.",
        "answer": "-2",
        "answerType": "numeric",
        "solution": [
          "Complete the square: $(x + 3)^2 = x^2 + 6x + 9$, so $(x + 3)^2 - 1 = 0$.",
          "This gives $(x + 3)^2 = 1$, so $x + 3 = \\pm 1$.",
          "Therefore $x = -2$ or $x = -4$, and the larger root is $x = -2$."
        ],
        "hint": "Half of $6$ is $3$; square $3$ to complete the square."
      }
    }
  },
  "m10-measurement-trig": {
    "elevation-depression": {
      "kind": "curated",
      "id": "intro-elevation-depression",
      "difficulty": "intro",
      "instance": {
        "prompt": "A ball is thrown vertically upward from a platform. Its height above the platform at time $t$ seconds is given by $h(t) = 50t - 5t^2 + 20$ metres, where $t \\geq 0$.\n\nFind the maximum height, in metres, that the ball reaches above the platform.",
        "answer": "145",
        "answerType": "numeric",
        "solution": [
          "Differentiate to get $h'(t) = 50 - 10t$ and set it to zero, giving $t = 5$ seconds.",
          "Check the second derivative: $h''(t) = -10 < 0$, confirming a maximum.",
          "Substitute $t = 5$ into $h(t) = 50(5) - 5(5)^2 + 20 = 250 - 125 + 20$.",
          "The maximum height above the platform is $145$ metres."
        ]
      }
    },
    "surveying-design": {
      "kind": "curated",
      "id": "intro-surveying-design",
      "difficulty": "intro",
      "instance": {
        "prompt": "A ladder $13$ m long leans against a wall, with its base $5$ m from the wall. How far up the wall does the ladder reach?",
        "answer": "12",
        "answerType": "numeric",
        "solution": [
          "So $h = \\sqrt{144} = 12$ m."
        ],
        "hint": "Pythagoras: $h = \\sqrt{13^2 - 5^2}$."
      }
    }
  },
  "m10-probability-conditional": {
    "two-way-venn": {
      "kind": "curated",
      "id": "intro-two-way-venn",
      "difficulty": "intro",
      "instance": {
        "prompt": "A class has $20$ boys and $15$ girls. $8$ boys and $6$ girls study French. The rest study German. Given that a randomly chosen student studies French, what is the probability the student is a girl? Give your answer as a fraction in simplest form.",
        "answer": "6/14",
        "answerType": "numeric",
        "solution": [
          "Total French students = $8 + 6 = 14$.",
          "Given the student studies French, there are $6$ girls among these $14$ students.",
          "$\\Pr = \\dfrac{6}{14} = \\dfrac{3}{7}$."
        ],
        "hint": "Among French students, how many are girls out of the total French students?"
      }
    },
    "trees-without-replacement": {
      "kind": "curated",
      "id": "intro-trees-without-replacement",
      "difficulty": "intro",
      "instance": {
        "prompt": "A bag contains 3 green and 2 yellow marbles. Two marbles are drawn without replacement. Find $\\Pr(\\text{Y then G})$ as a fraction in lowest terms.",
        "answer": "6/20",
        "answerType": "numeric",
        "solution": [
          "$\\Pr(\\text{Y first}) = \\dfrac{2}{5}$.",
          "After removing one yellow, there are 3 green out of 4 total, so $\\Pr(\\text{G second} \\mid \\text{Y first}) = \\dfrac{3}{4}$.",
          "$\\Pr(\\text{Y then G}) = \\dfrac{2}{5} \\cdot \\dfrac{3}{4} = \\dfrac{6}{20} = \\dfrac{3}{10}$."
        ],
        "hint": "First draw: 2 yellow out of 5 total. Without replacement, second draw: 3 green out of 4 remaining."
      }
    }
  },
  "m10-algebra-algorithms": {
    "pseudocode-loops": {
      "kind": "curated",
      "id": "intro-pseudocode-loops",
      "difficulty": "intro",
      "instance": {
        "prompt": "What does the following pseudocode compute? Type one word: 'sum', 'product', 'max', or 'min'.\n\n\nanswer:     product\nanswerType: exact\nsolution:   Running product of integers $1$ to $20$, i.e., $20!$.\nhint:       Each iteration multiplies the running total by the next value of $i$.\nchoices:    (none — open response)",
        "answer": "product",
        "answerType": "exact",
        "solution": [
          "The loop starts with $P = 1$ and iterates $i$ from $1$ to $20$.",
          "Each iteration multiplies $P$ by $i$, producing $P = 1 \\times 2 \\times 3 \\times \\dots \\times 20 = 20!$.",
          "The algorithm computes the product of integers $1$ to $20$."
        ]
      }
    }
  },
  "m10-algebra-linear-fractions": {
    "algebraic-denominators": {
      "kind": "curated",
      "id": "intro-algebraic-denominators",
      "difficulty": "intro",
      "instance": {
        "prompt": "Solve $\\dfrac{2}{x} = \\dfrac{1}{3}$. State $x$.",
        "answer": "6",
        "answerType": "numeric",
        "solution": [
          "Multiply both sides by $3$: $6 = x$, so $x = 6$."
        ],
        "hint": "Cross-multiply: $2 \\cdot 3 = 1 \\cdot x$."
      }
    }
  },
  "m10-space-networks": {
    "euler-polyhedra": {
      "kind": "curated",
      "id": "intro-euler-polyhedra",
      "difficulty": "intro",
      "instance": {
        "prompt": "A triangular prism has 5 faces and 6 vertices. How many edges does it have?",
        "answer": "9",
        "answerType": "numeric",
        "solution": [
          "Solve: E = 9."
        ],
        "hint": "Use F + V = E + 2, so E = F + V − 2."
      }
    }
  }
}
