// The coverage contract. Every study-design content point is listed here with a
// stable id and the verbatim (lightly abbreviated) text. Each topic declares which
// dot-point ids it covers, and scripts/check-coverage.ts asserts that every id below
// is claimed by >= 1 topic.
//
// Sources:
//   - VCE Mathematics Study Design 2023–2027, Mathematical Methods Units 1 & 2
//     (Areas of Study 1–4 for each unit).
//   - Victorian Curriculum F-10 Version 2.0, Level 10 Mathematics
//     (Strands: Number, Algebra, Measurement, Space, Statistics, Probability).

export interface DotPoint {
  id: string
  unit: 1 | 2 | 7 | 8 | 9 | 10 | '10A'
  /** Area of study / strand number 1–6. For VCE units 1–2 this is AoS 1–4; for Foundation levels this is the strand number. */
  aos: number
  aosName: string
  text: string
  /** Original Victorian Curriculum F-10 V2.0 content description code, e.g. `VC2M7N01`. Optional — only set on the Foundation levels. */
  code?: string
}

/** A Foundation "Strand" (high-level area of mathematics). Foundation levels (7, 8, 9, 10, 10A) all share the same six strands. */
export interface Strand {
  /** 1 = Number, 2 = Algebra, 3 = Measurement, 4 = Space, 5 = Statistics, 6 = Probability. */
  id: 1 | 2 | 3 | 4 | 5 | 6
  name: string
  /** A short blurb shown on the strand header / card. */
  description: string
}

export const DOT_POINTS: DotPoint[] = [
  // ---------------- Unit 1, AoS 1: Functions, relations and graphs ----------------
  {
    id: 'u1-fr-1',
    unit: 1,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'functions and function notation, domain, co-domain and range, representation of a function by rule, graph and table, inverse functions and their graphs',
  },
  {
    id: 'u1-fr-2',
    unit: 1,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'qualitative interpretation of features of graphs of functions, including real data not represented by a rule, with approximate location of intercepts, stationary points and points of inflection',
  },
  {
    id: 'u1-fr-3',
    unit: 1,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'graphs of power functions x^n for n = ±2, ±1, 1/2, 1, 2, 3, 4, and transformations to the form a(x+b)^n + c',
  },
  {
    id: 'u1-fr-4',
    unit: 1,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'graphs of polynomial functions of low degree, and interpretation of key features of these graphs',
  },

  // ---------------- Unit 1, AoS 2: Algebra, number and structure ----------------
  {
    id: 'u1-al-1',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'use of symbolic notation to develop algebraic expressions and represent functions, relations, equations, and systems of simultaneous equations',
  },
  {
    id: 'u1-al-2',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'substitution into, and manipulation of, these expressions',
  },
  {
    id: 'u1-al-3',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'recognition of equivalent expressions and simplification of algebraic expressions, use of distributive and exponent laws applied to polynomial and power functions',
  },
  {
    id: 'u1-al-4',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'use of parameters to represent families of functions and determination of rules of simple functions and relations from given information',
  },
  {
    id: 'u1-al-5',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'transformations of the plane: dilations (parallel to an axis and from an axis), reflections in an axis and translations, applied to basic functions and relations',
  },
  {
    id: 'u1-al-6',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'the connection between roots of a polynomial, its factors and horizontal axis intercepts, including the remainder, factor and rational root theorems',
  },
  {
    id: 'u1-al-7',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'solution of polynomial equations of low degree, numerically, graphically and algebraically, including the bisection method algorithm',
  },
  {
    id: 'u1-al-8',
    unit: 1,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'solution of a set of simultaneous linear equations, and equations of the form y = f(x), numerically, graphically and algebraically',
  },

  // ---------------- Unit 1, AoS 3: Calculus ----------------
  {
    id: 'u1-ca-1',
    unit: 1,
    aos: 3,
    aosName: 'Calculus',
    text: 'average and instantaneous rates of change in practical contexts; instantaneous rate of change as a limiting case of the average rate of change',
  },
  {
    id: 'u1-ca-2',
    unit: 1,
    aos: 3,
    aosName: 'Calculus',
    text: 'interpretation of graphs of empirical data with respect to rate of change (temperature, motion graphs, height of water in containers) with informal consideration of continuity and smoothness',
  },
  {
    id: 'u1-ca-3',
    unit: 1,
    aos: 3,
    aosName: 'Calculus',
    text: 'use of gradient of a tangent at a point to describe instantaneous rate of change, including where the rate of change is positive, negative or zero, and the relationship of the gradient function to the original graph',
  },

  // ---------------- Unit 1, AoS 4: Data analysis, probability and statistics ----------------
  {
    id: 'u1-pr-1',
    unit: 1,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'random experiments, sample spaces, outcomes, elementary and compound events, random variables and the distribution of results of experiments',
  },
  {
    id: 'u1-pr-2',
    unit: 1,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'simulation using random generators (coins, dice, spinners, pseudo-random generators) and display/interpretation of results, including proportions in samples',
  },
  {
    id: 'u1-pr-3',
    unit: 1,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'addition and multiplication principles for counting',
  },
  {
    id: 'u1-pr-4',
    unit: 1,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'combinations including the concept of a selection, computation of nCr, and application of counting techniques to probability',
  },

  // ---------------- Unit 2, AoS 1: Functions, relations and graphs ----------------
  {
    id: 'u2-fr-1',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'the unit circle, radians, arc length and sine, cosine and tangent as functions of a real variable',
  },
  {
    id: 'u2-fr-2',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'the relationship sin x ≈ x for small values of x, and related small-angle behaviour',
  },
  {
    id: 'u2-fr-3',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'exact values for sine, cosine and tangent of 0, π/6, π/4, π/3, π/2 and their multiples',
  },
  {
    id: 'u2-fr-4',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'symmetry properties, complementary relations and periodicity properties for sine, cosine and tangent functions',
  },
  {
    id: 'u2-fr-5',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'circular functions of the form y = a f(n(x+b)) + c and their graphs, where f is sine, cosine or tangent',
  },
  {
    id: 'u2-fr-6',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'simple applications of sine and cosine functions, interpretation of period, amplitude and mean value in modelling contexts',
  },
  {
    id: 'u2-fr-7',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'exponential functions of the form y = a·b^(n(x+b)) + c and their graphs',
  },
  {
    id: 'u2-fr-8',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'logarithmic functions y = log_a(x) and their graphs, as the inverse of y = a^x, including a^(log_a x) = x and log_a(a^x) = x',
  },
  {
    id: 'u2-fr-9',
    unit: 2,
    aos: 1,
    aosName: 'Functions, relations and graphs',
    text: 'simple applications of exponential functions: initial value, rate of growth or decay, half-life, doubling time and long-run value',
  },

  // ---------------- Unit 2, AoS 2: Algebra, number and structure ----------------
  {
    id: 'u2-al-1',
    unit: 2,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'use of inverse functions and transformations to solve equations of the form a f(n(x+b)) + c = k where f is sine, cosine, tangent or a^x, using exact or approximate values on a given domain',
  },
  {
    id: 'u2-al-2',
    unit: 2,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: 'exponent laws and logarithm laws, including their application to the solution of simple exponential equations',
  },
  {
    id: 'u2-al-3',
    unit: 2,
    aos: 2,
    aosName: 'Algebra, number and structure',
    text: "numerical approximation of roots of cubic polynomial functions using Newton's method algorithm",
  },

  // ---------------- Unit 2, AoS 3: Calculus ----------------
  {
    id: 'u2-ca-1',
    unit: 2,
    aos: 3,
    aosName: 'Calculus',
    text: 'informal treatment of the gradient of the tangent as a limit, and the limit definition of the derivative f\'(x) = lim h→0 (f(x+h) − f(x))/h',
  },
  {
    id: 'u2-ca-2',
    unit: 2,
    aos: 3,
    aosName: 'Calculus',
    text: "the central difference approximation f'(x) ≈ (f(x+h) − f(x−h))/2h and its graphical interpretation",
  },
  {
    id: 'u2-ca-3',
    unit: 2,
    aos: 3,
    aosName: 'Calculus',
    text: 'the derivative as the gradient of the graph at a point, its representation by a gradient function, and as a rate of change',
  },
  {
    id: 'u2-ca-4',
    unit: 2,
    aos: 3,
    aosName: 'Calculus',
    text: 'differentiation of polynomial functions by rule',
  },
  {
    id: 'u2-ca-5',
    unit: 2,
    aos: 3,
    aosName: 'Calculus',
    text: 'applications of differentiation: instantaneous rates of change, stationary values, local maxima/minima, points of inflection, motion graphs, and maximum/minimum problems with modelling domain',
  },
  {
    id: 'u2-ca-6',
    unit: 2,
    aos: 3,
    aosName: 'Calculus',
    text: 'anti-differentiation as the inverse of differentiation, families of curves with the same gradient function, and use of a boundary condition to determine a specific anti-derivative',
  },

  // ---------------- Unit 2, AoS 4: Data analysis, probability and statistics ----------------
  {
    id: 'u2-pr-1',
    unit: 2,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'probability of elementary and compound events and their representation as lists, grids, Venn diagrams, tables and tree diagrams',
  },
  {
    id: 'u2-pr-2',
    unit: 2,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'the addition rule Pr(A∪B) = Pr(A) + Pr(B) − Pr(A∩B), and for mutually exclusive events Pr(A∩B) = 0',
  },
  {
    id: 'u2-pr-3',
    unit: 2,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'conditional probability in terms of reduced sample space, Pr(A|B) = Pr(A∩B)/Pr(B), and Pr(A∩B) = Pr(A|B)Pr(B)',
  },
  {
    id: 'u2-pr-4',
    unit: 2,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'the law of total probability for two events',
  },
  {
    id: 'u2-pr-5',
    unit: 2,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'the relations for independent events Pr(A∩B) = Pr(A)Pr(B), and independence in terms of conditional probability',
  },
  {
    id: 'u2-pr-6',
    unit: 2,
    aos: 4,
    aosName: 'Data analysis, probability and statistics',
    text: 'simulation to estimate probabilities involving selection with and without replacement',
  },

  // ---------------- Foundation (Year 10 Mathematics) ----------------
  // Victorian Curriculum F-10 Version 2.0 — Level 10 Mathematics.
  // Six strands: Number, Algebra, Measurement, Space, Statistics, Probability.
  {
    id: 'm10-n-1',
    unit: 10,
    aos: 1,
    aosName: 'Number',
    text: 'recognise the effect of using approximations of real numbers in repeated calculations',
  },
  {
    id: 'm10-a-1',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'factorise algebraic expressions by taking out a common algebraic factor',
  },
  {
    id: 'm10-a-2',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'simplify algebraic products and quotients using exponent laws',
  },
  {
    id: 'm10-a-3',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'apply the 4 operations to simple algebraic fractions with numerical or single variable denominators',
  },
  {
    id: 'm10-a-4',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'expand binomial products and factorise monic quadratic expressions using a variety of strategies',
  },
  {
    id: 'm10-a-5',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'substitute values into formulas to determine an unknown and rearrange formulas to solve for a particular term',
  },
  {
    id: 'm10-a-6',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'implement algorithms that use data structures using pseudocode or a general purpose programming language',
  },
  {
    id: 'm10-a-7',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve problems involving linear equations, including those derived from formulas',
  },
  {
    id: 'm10-a-8',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve linear inequalities and graph their solutions on a number line',
  },
  {
    id: 'm10-a-9',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve simultaneous linear equations, using algebraic and graphical techniques including using digital tools',
  },
  {
    id: 'm10-a-10',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve problems involving gradients of parallel and perpendicular lines',
  },
  {
    id: 'm10-a-11',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'explore the connection between algebraic and graphical representations of relations such as simple quadratic, reciprocal, circle and exponential, using digital tools as appropriate',
  },
  {
    id: 'm10-a-12',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve linear equations involving simple algebraic fractions',
  },
  {
    id: 'm10-a-13',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve simple quadratic equations using a range of strategies, including null factor law',
  },
  {
    id: 'm10-a-14',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve simple exponential equations',
  },
  {
    id: 'm10-a-15',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'use mathematical modelling to solve applied problems involving inverse proportion, growth and decay, including in financial contexts to establish the compound interest formula as repeated applications of simple interest; formulate problems, choosing to apply linear, quadratic or exponential models; interpret solutions in terms of the situation; evaluate and modify models as necessary and report assumptions, methods and findings',
  },
  {
    id: 'm10-a-16',
    unit: 10,
    aos: 2,
    aosName: 'Algebra',
    text: 'solve equations graphically or using systematic numerical guess-check-and-refine with digital tools, with consideration of whether all solutions have been found',
  },
  {
    id: 'm10-m-1',
    unit: 10,
    aos: 3,
    aosName: 'Measurement',
    text: 'solve problems involving the surface area and volume of composite objects using appropriate units',
  },
  {
    id: 'm10-m-2',
    unit: 10,
    aos: 3,
    aosName: 'Measurement',
    text: 'interpret and use logarithmic scales in applied contexts involving small and large quantities and change',
  },
  {
    id: 'm10-m-3',
    unit: 10,
    aos: 3,
    aosName: 'Measurement',
    text: 'solve practical problems by applying Pythagoras’ theorem and trigonometry to right-angled triangles, including problems involving direction and angles of elevation and depression',
  },
  {
    id: 'm10-m-4',
    unit: 10,
    aos: 3,
    aosName: 'Measurement',
    text: 'use mathematical modelling to solve practical problems involving direct and inverse proportion and scaling of objects; formulate problems and interpret solutions in terms of the situation, including the impact of measurement errors on the accuracy of results; evaluate and modify models as necessary, and report assumptions, methods and findings',
  },
  {
    id: 'm10-sp-1',
    unit: 10,
    aos: 4,
    aosName: 'Space',
    text: 'apply deductive reasoning to formulate proofs involving shapes in the plane and use theorems to solve spatial problems',
  },
  {
    id: 'm10-sp-2',
    unit: 10,
    aos: 4,
    aosName: 'Space',
    text: 'interpret networks and network diagrams used to represent relationships in practical situations and describe connectedness',
  },
  {
    id: 'm10-st-1',
    unit: 10,
    aos: 5,
    aosName: 'Statistics',
    text: 'compare data distributions for continuous numerical variables using quartiles and interquartile range and appropriate data displays including boxplots, histograms and dot plots; discuss data in terms of centre, spread, shape and outliers in the context of the data',
  },
  {
    id: 'm10-st-2',
    unit: 10,
    aos: 5,
    aosName: 'Statistics',
    text: 'construct scatterplots and consider a line of good fit; comment on the association between the 2 numerical variables in terms of strength, direction and linearity informally using a line of good fit by eye and using digital tools to compare and discuss the reliability of any predictions',
  },
  {
    id: 'm10-st-3',
    unit: 10,
    aos: 5,
    aosName: 'Statistics',
    text: 'construct two-way tables and discuss possible relationship between categorical variables',
  },
  {
    id: 'm10-st-4',
    unit: 10,
    aos: 5,
    aosName: 'Statistics',
    text: 'analyse claims, inferences and conclusions of statistical reports in the media and other places, by linking claims to displays, statistics and representative data, including ethical considerations and identification of potential sources of bias',
  },
  {
    id: 'm10-st-5',
    unit: 10,
    aos: 5,
    aosName: 'Statistics',
    text: 'plan and conduct statistical investigations of situations that involve bivariate data, including where the independent variable is time; evaluate and report findings of any inferences',
  },
  {
    id: 'm10-p-1',
    unit: 10,
    aos: 6,
    aosName: 'Probability',
    text: 'use the language of ‘if … then …’, ‘given’, ‘of’ and ‘knowing that’ to investigate conditional statements and identify common mistakes in interpreting such language, and involving conditional probability; design and conduct simulations using digital tools to model conditional probability and interpret results',
  },
  {
    id: 'm10-p-2',
    unit: 10,
    aos: 6,
    aosName: 'Probability',
    text: 'describe the results of two- and three-step chance experiments, both with and without replacements, assign probabilities to outcomes and determine probabilities of events; investigate the concept of independence',
  },

  // ---------------- Foundation Level 7 ----------------
  // Victorian Curriculum F-10 Version 2.0 — Level 7 Mathematics.
  {
    id: 'l7-n-1',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N01',
    text: 'describe the relationship between perfect square numbers and square roots, and use squares of numbers and square roots of perfect square numbers to solve problems',
  },
  {
    id: 'l7-n-2',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N02',
    text: 'represent natural numbers in expanded notation using powers of 10, and as products of powers of prime numbers using exponent notation',
  },
  {
    id: 'l7-n-3',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N03',
    text: 'find equivalent representations of rational numbers and represent positive and negative rational numbers and mixed numbers on a number line',
  },
  {
    id: 'l7-n-4',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N04',
    text: 'round decimals to a given accuracy appropriate to the context and use appropriate rounding and estimation to check the reasonableness of computations',
  },
  {
    id: 'l7-n-5',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N05',
    text: 'multiply and divide fractions and decimals using efficient mental and written strategies, and digital tools',
  },
  {
    id: 'l7-n-6',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N06',
    text: 'use the 4 operations with positive rational numbers, including fractions and decimals, to solve problems using efficient mental and written calculation strategies',
  },
  {
    id: 'l7-n-7',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N07',
    text: 'find percentages of quantities and express one quantity as a percentage of another, with and without digital tools',
  },
  {
    id: 'l7-n-8',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N08',
    text: 'compare, order and solve problems involving addition and subtraction of integers',
  },
  {
    id: 'l7-n-9',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N09',
    text: 'recognise, represent and solve problems involving ratios',
  },
  {
    id: 'l7-n-10',
    unit: 7,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M7N10',
    text: 'use mathematical modelling to solve practical problems involving rational numbers and percentages, including financial contexts such as "best buys"',
  },
  {
    id: 'l7-a-1',
    unit: 7,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M7A01',
    text: 'recognise and use variables to represent everyday formulas algebraically and substitute values into formulas to determine an unknown',
  },
  {
    id: 'l7-a-2',
    unit: 7,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M7A02',
    text: 'apply the associative, commutative and distributive laws to aid mental and written computation, and formulate algebraic expressions using constants, variables, operations and brackets',
  },
  {
    id: 'l7-a-3',
    unit: 7,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M7A03',
    text: 'solve one-variable linear equations of increasing complexity with natural number solutions; verify equation solutions by substitution',
  },
  {
    id: 'l7-a-4',
    unit: 7,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M7A04',
    text: 'investigate, interpret and describe relationships between variables represented in graphs of functions developed from authentic data',
  },
  {
    id: 'l7-a-5',
    unit: 7,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M7A05',
    text: 'generate tables of values from visually changing patterns or the rule of a function; describe and plot these relationships on the Cartesian plane',
  },
  {
    id: 'l7-a-6',
    unit: 7,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M7A06',
    text: 'manipulate formulas involving several variables using digital tools, and describe the effect of systematic variation in the values of the variables',
  },
  {
    id: 'l7-m-1',
    unit: 7,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M7M01',
    text: 'establish the formulas for areas of rectangles, triangles and parallelograms and use these in problem-solving',
  },
  {
    id: 'l7-m-2',
    unit: 7,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M7M02',
    text: 'solve problems involving the volume of right prisms including rectangular and triangular prisms, using established formulas and appropriate units',
  },
  {
    id: 'l7-m-3',
    unit: 7,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M7M03',
    text: 'compare the circumference of circles in relation to their radius and diameter, and establish measurement formulas for the circumference of a circle',
  },
  {
    id: 'l7-m-4',
    unit: 7,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M7M04',
    text: 'identify corresponding, alternate and co-interior relationships between angles formed when parallel lines are crossed by a transversal; use them to solve problems and explain reasons',
  },
  {
    id: 'l7-m-5',
    unit: 7,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M7M05',
    text: 'demonstrate that the interior angle sum of a triangle in the plane is 180° and apply this to determine the interior angle sum of other shapes and the size of unknown angles',
  },
  {
    id: 'l7-m-6',
    unit: 7,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M7M06',
    text: 'use mathematical modelling to solve practical problems involving ratios of lengths, areas and volumes',
  },
  {
    id: 'l7-sp-1',
    unit: 7,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M7SP01',
    text: 'represent three-dimensional objects in 2 dimensions; discuss and reason about the advantages and disadvantages of different representations',
  },
  {
    id: 'l7-sp-2',
    unit: 7,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M7SP02',
    text: 'classify triangles, quadrilaterals and other polygons according to their side and angle properties; identify and reason about relationships',
  },
  {
    id: 'l7-sp-3',
    unit: 7,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M7SP03',
    text: 'describe the effect of transformations of a set of points using coordinates in the Cartesian plane, including translations, reflections in an axis, and rotations about the origin',
  },
  {
    id: 'l7-sp-4',
    unit: 7,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M7SP04',
    text: 'design algorithms involving a sequence of steps and decisions that will sort and classify sets of shapes according to their attributes, and describe how the algorithms work',
  },
  {
    id: 'l7-st-1',
    unit: 7,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M7ST01',
    text: 'acquire data sets for discrete and continuous numerical variables and calculate the range, median, mean and mode; make and justify decisions about which measures of central tendency provide useful insights',
  },
  {
    id: 'l7-st-2',
    unit: 7,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M7ST02',
    text: 'create different types of displays of numerical data, including dot plots and stem-and-leaf plots, and describe and compare the distribution of data, commenting on the shape, centre and spread including outliers',
  },
  {
    id: 'l7-st-3',
    unit: 7,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M7ST03',
    text: 'plan and conduct statistical investigations for issues involving discrete and continuous numerical data, and data collected from primary and secondary sources; analyse and interpret distributions of data and report findings',
  },
  {
    id: 'l7-p-1',
    unit: 7,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M7P01',
    text: 'identify the sample space for single-stage experiments; assign probabilities to the possible outcomes and predict relative frequencies for related experiments',
  },
  {
    id: 'l7-p-2',
    unit: 7,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M7P02',
    text: 'conduct repeated chance experiments and run simulations with a large number of trials using digital tools; compare predicted with observed results, explaining the differences and the effect of sample size',
  },

  // ---------------- Foundation Level 8 ----------------
  {
    id: 'l8-n-1',
    unit: 8,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M8N01',
    text: 'recognise irrational numbers as numbers that cannot develop from the division of integer values by natural numbers and terminating or recurring decimals',
  },
  {
    id: 'l8-n-2',
    unit: 8,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M8N02',
    text: 'establish and apply the exponent laws with positive integer exponents and the zero exponent, using exponent notation with numbers',
  },
  {
    id: 'l8-n-3',
    unit: 8,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M8N03',
    text: 'convert between fractions and terminating or recurring decimals, using digital tools as appropriate',
  },
  {
    id: 'l8-n-4',
    unit: 8,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M8N04',
    text: 'use the 4 operations with integers and with rational numbers, choosing and using efficient mental and written strategies, and digital tools where appropriate, and making estimates for these computations',
  },
  {
    id: 'l8-n-5',
    unit: 8,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M8N05',
    text: 'solve problems involving the use of percentages, including percentage increases and decreases and percentage error, with and without digital tools',
  },
  {
    id: 'l8-n-6',
    unit: 8,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M8N06',
    text: 'use mathematical modelling to solve practical problems involving rational numbers and percentages, including financial contexts involving profit and loss',
  },
  {
    id: 'l8-a-1',
    unit: 8,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M8A01',
    text: 'create, expand, factorise, rearrange and simplify linear expressions, applying the associative, commutative, identity, distributive and inverse properties',
  },
  {
    id: 'l8-a-2',
    unit: 8,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M8A02',
    text: 'graph linear relations on the Cartesian plane using digital tools where appropriate; solve linear equations and one-variable inequalities using graphical and algebraic techniques; verify solutions by substitution',
  },
  {
    id: 'l8-a-3',
    unit: 8,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M8A03',
    text: 'use mathematical modelling to solve applied problems involving linear relations, including financial contexts involving profit and loss',
  },
  {
    id: 'l8-a-4',
    unit: 8,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M8A04',
    text: 'use algorithms and related testing procedures to identify and correct errors',
  },
  {
    id: 'l8-a-5',
    unit: 8,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M8A05',
    text: 'experiment with linear functions and relations using digital tools, making and testing conjectures and generalising emerging patterns',
  },
  {
    id: 'l8-m-1',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M01',
    text: 'solve problems involving the area and perimeter of irregular and composite shapes using appropriate units',
  },
  {
    id: 'l8-m-2',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M02',
    text: 'solve problems involving the volume and capacity of right prisms using appropriate units',
  },
  {
    id: 'l8-m-3',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M03',
    text: 'solve problems involving the circumference and area of a circle using formulas and appropriate units',
  },
  {
    id: 'l8-m-4',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M04',
    text: 'solve problems involving time and duration, including using 12- and 24-hour time across multiple time zones',
  },
  {
    id: 'l8-m-5',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M05',
    text: 'recognise and use rates to solve problems involving the comparison of 2 related quantities of different units of measure',
  },
  {
    id: 'l8-m-6',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M06',
    text: 'use Pythagoras\' theorem to solve problems involving the side lengths of right-angled triangles',
  },
  {
    id: 'l8-m-7',
    unit: 8,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M8M07',
    text: 'use mathematical modelling to solve practical problems involving ratios and rates, including distance-time problems for travel at a constant speed and financial contexts',
  },
  {
    id: 'l8-sp-1',
    unit: 8,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M8SP01',
    text: 'identify the conditions for congruence and similarity of triangles and explain the conditions for other sets of common shapes to be congruent or similar, including those formed by transformations',
  },
  {
    id: 'l8-sp-2',
    unit: 8,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M8SP02',
    text: 'establish properties of quadrilaterals using congruent triangles and angle properties, and solve related problems explaining reasoning',
  },
  {
    id: 'l8-sp-3',
    unit: 8,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M8SP03',
    text: 'describe in different ways the position and location of three-dimensional objects in 3 dimensions, including using a three-dimensional Cartesian coordinate system with the use of dynamic geometry software or other digital tools',
  },
  {
    id: 'l8-sp-4',
    unit: 8,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M8SP04',
    text: 'design and test algorithms involving a sequence of steps and decisions that identify congruency or similarity of shapes, and describe how the algorithm works',
  },
  {
    id: 'l8-st-1',
    unit: 8,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M8ST01',
    text: 'distinguish between a population and a sample, and investigate techniques for data collection including census, sampling, experiment and observation, and explain the practicalities and implications of obtaining data through these techniques',
  },
  {
    id: 'l8-st-2',
    unit: 8,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M8ST02',
    text: 'analyse and report on the distribution of data from primary and secondary sources using random and non-random sampling techniques',
  },
  {
    id: 'l8-st-3',
    unit: 8,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M8ST03',
    text: 'compare variations in distributions and proportions obtained from random samples of the same size drawn from a population and recognise the effect of sample size on this variation',
  },
  {
    id: 'l8-st-4',
    unit: 8,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M8ST04',
    text: 'plan and conduct statistical investigations involving samples of a population; use ethical and fair methods to make inferences about the population and report findings, acknowledging uncertainty',
  },
  {
    id: 'l8-p-1',
    unit: 8,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M8P01',
    text: 'recognise that complementary events have a combined probability of one; use this relationship to calculate probabilities in applied contexts',
  },
  {
    id: 'l8-p-2',
    unit: 8,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M8P02',
    text: 'determine all possible outcome combinations for 2 events, using two-way tables, tree diagrams and Venn diagrams, and use these to determine probabilities of specific events in practical situations',
  },
  {
    id: 'l8-p-3',
    unit: 8,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M8P03',
    text: 'conduct repeated chance experiments and simulations, using digital tools to determine probabilities for compound events, and describe results',
  },

  // ---------------- Foundation Level 9 ----------------
  {
    id: 'l9-n-1',
    unit: 9,
    aos: 1,
    aosName: 'Number',
    code: 'VC2M9N01',
    text: 'recognise that the real number system includes the rational numbers and the irrational numbers, and solve problems involving real numbers with and without using digital tools',
  },
  {
    id: 'l9-a-1',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A01',
    text: 'apply the exponent laws to numerical expressions with integer exponents and the zero exponent, and extend to variables',
  },
  {
    id: 'l9-a-2',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A02',
    text: 'simplify algebraic expressions, apply the distributive law to expand algebraic expressions including binomial products, and factorise monic quadratic expressions',
  },
  {
    id: 'l9-a-3',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A03',
    text: 'sketch linear graphs of equations in various algebraic forms, using the coordinates of 2 points, and solve linear equations',
  },
  {
    id: 'l9-a-4',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A04',
    text: 'find the gradient of a line segment, the midpoint of the line interval and the distance between 2 distinct points on the Cartesian plane',
  },
  {
    id: 'l9-a-5',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A05',
    text: 'identify and graph quadratic functions, solve quadratic equations graphically and numerically, and use null factor law to solve monic quadratic equations with integer roots algebraically',
  },
  {
    id: 'l9-a-6',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A06',
    text: 'use mathematical modelling to solve applied problems involving change, including financial contexts involving simple interest, choosing linear, quadratic or other simple functions',
  },
  {
    id: 'l9-a-7',
    unit: 9,
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M9A07',
    text: 'experiment with the effects of the variation of parameters on graphs of related functions, using digital tools, making connections between graphical and algebraic representations',
  },
  {
    id: 'l9-m-1',
    unit: 9,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M9M01',
    text: 'solve problems involving the volume and surface area of right prisms, cylinders and composite objects using appropriate units',
  },
  {
    id: 'l9-m-2',
    unit: 9,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M9M02',
    text: 'solve problems involving very small and very large measurements, timescales and intervals expressed in scientific notation',
  },
  {
    id: 'l9-m-3',
    unit: 9,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M9M03',
    text: 'solve spatial problems, applying angle properties, scale, similarity, ratio, Pythagoras\' theorem and trigonometry in right-angled triangles',
  },
  {
    id: 'l9-m-4',
    unit: 9,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M9M04',
    text: 'calculate and interpret absolute, relative and percentage errors in measurements',
  },
  {
    id: 'l9-m-5',
    unit: 9,
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M9M05',
    text: 'use mathematical modelling to solve practical problems involving direct proportion, rates, ratio and scale, including financial contexts',
  },
  {
    id: 'l9-sp-1',
    unit: 9,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M9SP01',
    text: 'recognise the constancy of the sine, cosine and tangent ratios for a given angle in right-angled triangles using properties of similarity',
  },
  {
    id: 'l9-sp-2',
    unit: 9,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M9SP02',
    text: 'apply the enlargement transformation to shapes and objects using dynamic geometry software as appropriate; identify and explain, using language of similarity, ratio and scale, aspects that remain the same and those that change',
  },
  {
    id: 'l9-sp-3',
    unit: 9,
    aos: 4,
    aosName: 'Space',
    code: 'VC2M9SP03',
    text: 'design, test and refine algorithms involving a sequence of steps and decisions based on geometric constructions and theorems; discuss and evaluate refinements',
  },
  {
    id: 'l9-st-1',
    unit: 9,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M9ST01',
    text: 'analyse reports of surveys in digital media and elsewhere for information on how data was obtained around everyday questions and issues involving at least one numerical and at least one categorical variable, to estimate population means and medians',
  },
  {
    id: 'l9-st-2',
    unit: 9,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M9ST02',
    text: 'analyse how different sampling methods, and different samples using the same method, can affect the results of surveys and how choice of representation can be used to support a particular point of view',
  },
  {
    id: 'l9-st-3',
    unit: 9,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M9ST03',
    text: 'represent the distribution of multiple data sets for numerical variables using comparative representations such as back-to-back stem-and-leaf plots and histograms; describe data, using terms including "skewed", "symmetric" and "bi-modal"',
  },
  {
    id: 'l9-st-4',
    unit: 9,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M9ST04',
    text: 'choose appropriate forms of display or visualisation for a given type of data; justify selections and interpret displays for a given context',
  },
  {
    id: 'l9-st-5',
    unit: 9,
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M9ST05',
    text: 'plan and conduct statistical investigations involving the collection and analysis of different kinds of data; report findings and discuss the strength of evidence to support any conclusions',
  },
  {
    id: 'l9-p-1',
    unit: 9,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M9P01',
    text: 'list all outcomes for two-step chance experiments both with and without replacement, using lists, tree diagrams, tables or arrays; assign probabilities to outcomes and events',
  },
  {
    id: 'l9-p-2',
    unit: 9,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M9P02',
    text: 'calculate relative frequencies from given or collected data to estimate probabilities of events involving "and", inclusive "or" and exclusive "or"',
  },
  {
    id: 'l9-p-3',
    unit: 9,
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M9P03',
    text: 'design and conduct repeated chance experiments and simulations using digital tools to estimate probabilities that cannot be determined exactly',
  },

  // ---------------- Foundation Level 10A ----------------
  // Note: there is no achievement standard for Level 10A; these dot points
  // are organised for extension into VCE Mathematical Methods.
  {
    id: 'l10a-an-1',
    unit: '10A',
    aos: 1,
    aosName: 'Number',
    code: 'VC2M10AN01',
    text: 'define rational and irrational numbers and perform operations with surds and fractional indices',
  },
  {
    id: 'l10a-an-2',
    unit: '10A',
    aos: 1,
    aosName: 'Number',
    code: 'VC2M10AN02',
    text: 'perform operations on numbers involving fractional exponents and surds',
  },
  {
    id: 'l10a-an-3',
    unit: '10A',
    aos: 1,
    aosName: 'Number',
    code: 'VC2M10AN03',
    text: 'use the definition of a logarithm to establish and apply the laws of logarithms and investigate logarithmic scales in measurement',
  },
  {
    id: 'l10a-aa-1',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA01',
    text: 'investigate the concept of a polynomial and apply the factor and remainder theorems to solve problems',
  },
  {
    id: 'l10a-aa-2',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA02',
    text: 'devise and use algorithms and simulations to solve mathematical problems',
  },
  {
    id: 'l10a-aa-3',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA03',
    text: 'simplify combinations of linear expressions with rational coefficients and the solution of related equations',
  },
  {
    id: 'l10a-aa-4',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA04',
    text: 'explore the inverse relationship between exponential functions and logarithmic functions and the solution of related equations',
  },
  {
    id: 'l10a-aa-5',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA05',
    text: 'describe, interpret, and sketch parabolas, hyperbolas, circles and exponential functions and their transformations',
  },
  {
    id: 'l10a-aa-6',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA06',
    text: 'apply understanding of polynomials to sketch a range of curves and describe the features of these curves from their equation',
  },
  {
    id: 'l10a-aa-7',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA07',
    text: 'factorise monic and non-monic quadratic expressions and solve a wide range of quadratic equations derived from a variety of contexts',
  },
  {
    id: 'l10a-aa-8',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA08',
    text: 'use function notation to describe the relationship between dependent and independent variables in modelling contexts',
  },
  {
    id: 'l10a-aa-9',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA09',
    text: 'solve linear and non-linear simultaneous equations using graphing or systematic guess-check-and-refine with digital tools',
  },
  {
    id: 'l10a-aa-10',
    unit: '10A',
    aos: 2,
    aosName: 'Algebra',
    code: 'VC2M10AA10',
    text: 'experiment with functions and relations using digital tools, making and testing conjectures and generalising emerging patterns',
  },
  {
    id: 'l10a-am-1',
    unit: '10A',
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M10AM01',
    text: 'solve problems involving surface area and volume of right pyramids, right cones, spheres and related composite solids',
  },
  {
    id: 'l10a-am-2',
    unit: '10A',
    aos: 3,
    aosName: 'Measurement',
    code: 'VC2M10AM02',
    text: 'explore the effect of increasingly small changes in the value of variables on the average rate of change and in relation to limiting values',
  },
  {
    id: 'l10a-asp-1',
    unit: '10A',
    aos: 4,
    aosName: 'Space',
    code: 'VC2M10ASP01',
    text: 'prove and apply relationships between angles and various lines associated with circles (radii, diameters, chords, tangents)',
  },
  {
    id: 'l10a-asp-2',
    unit: '10A',
    aos: 4,
    aosName: 'Space',
    code: 'VC2M10ASP02',
    text: 'establish the sine, cosine and area rules for any triangle and solve related problems',
  },
  {
    id: 'l10a-asp-3',
    unit: '10A',
    aos: 4,
    aosName: 'Space',
    code: 'VC2M10ASP03',
    text: 'establish the symmetrical properties of trigonometric functions; investigate angles of any magnitude and use the unit circle to identify points via arc lengths in radians',
  },
  {
    id: 'l10a-asp-4',
    unit: '10A',
    aos: 4,
    aosName: 'Space',
    code: 'VC2M10ASP04',
    text: 'solve simple trigonometric equations',
  },
  {
    id: 'l10a-asp-5',
    unit: '10A',
    aos: 4,
    aosName: 'Space',
    code: 'VC2M10ASP05',
    text: 'apply Pythagoras\' theorem and trigonometry to solving three-dimensional problems in right-angled triangles',
  },
  {
    id: 'l10a-asp-6',
    unit: '10A',
    aos: 4,
    aosName: 'Space',
    code: 'VC2M10ASP06',
    text: 'design, test and refine solutions to spatial problems using algorithms and digital tools; communicate and justify solutions',
  },
  {
    id: 'l10a-ast-1',
    unit: '10A',
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M10AST01',
    text: 'calculate and interpret the mean and standard deviation of data and use these to compare data sets; investigate the effect of individual data values, including outliers, on the standard deviation',
  },
  {
    id: 'l10a-ast-2',
    unit: '10A',
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M10AST02',
    text: 'identify measures of spread, and understand their interpretation and usefulness with respect to different data distributions',
  },
  {
    id: 'l10a-ast-3',
    unit: '10A',
    aos: 5,
    aosName: 'Statistics',
    code: 'VC2M10AST03',
    text: 'use digital tools to investigate bivariate numerical data sets; where appropriate use a straight line to describe the relationship allowing for variation, make predictions based on this straight line and discuss limitations',
  },
  {
    id: 'l10a-ap-1',
    unit: '10A',
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M10AP01',
    text: 'explore counting principles, and factorial notation as a representation that provides efficient counting in multiplicative contexts, including calculations of probabilities',
  },
  {
    id: 'l10a-ap-2',
    unit: '10A',
    aos: 6,
    aosName: 'Probability',
    code: 'VC2M10AP02',
    text: 'investigate reports of studies in digital media and elsewhere for information on their planning and implementation',
  },
]

/** The 6 Foundation strands (used by Year 7, 8, 9, 10, and 10A), in canonical order. */
export const STRANDS: Strand[] = [
  {
    id: 1,
    name: 'Number',
    description:
      'Real numbers, approximations, and the effect of repeated calculations on final results.',
  },
  {
    id: 2,
    name: 'Algebra',
    description:
      'Factorisation, exponent laws, equations, inequalities, functions, and modelling.',
  },
  {
    id: 3,
    name: 'Measurement',
    description:
      'Surface area, volume, logarithmic scales, Pythagoras and right-angled trigonometry.',
  },
  {
    id: 4,
    name: 'Space',
    description:
      'Geometric proofs in the plane and network diagrams of practical situations.',
  },
  {
    id: 5,
    name: 'Statistics',
    description:
      'Distributions, boxplots, scatterplots, two-way tables, and statistical investigations.',
  },
  {
    id: 6,
    name: 'Probability',
    description:
      'Conditional probability, multi-step chance experiments, and independence.',
  },
]

/** All strand ids, in order. Useful for iteration. */
export const STRAND_IDS: Strand['id'][] = STRANDS.map((s) => s.id)

export const DOT_POINT_IDS = DOT_POINTS.map((d) => d.id)
