/**
 * Bulk-seed an `intro`-level curated exercise for every lesson that
 * doesn't have one. Calls the regenerate endpoint at `difficulty:
 * 'intro'`, validates the result via the same gate the ladder uses, and
 * writes the successes into `src/content/_intros.ts` as a typed map.
 *
 * Usage:
 *   ANTHROPIC_AUTH_TOKEN=... npm run seed:intros
 *
 * Idempotent: re-running overwrites the sidecar. Failed lessons are
 * listed in stdout so a manual follow-up can author them.
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'

import { TOPICS } from '../src/content/topics'
import type {
  CuratedExercise,
  Difficulty,
  ExerciseInstance,
  Lesson,
  Topic,
} from '../src/content/types'
import { callRegenerate } from '../server/m3'
import { log } from '../server/logger'

const BASE_URL = process.env.ANTHROPIC_BASE_URL ?? 'https://api.minimaxi.com/anthropic'
const AUTH_TOKEN = process.env.ANTHROPIC_AUTH_TOKEN ?? ''
const MODEL = process.env.ANTHROPIC_MODEL ?? 'MiniMax-M3'
const OUT = path.join(process.cwd(), 'src/content/_intros.ts')
const MAX_ATTEMPTS = 3

interface SeedEntry {
  topicId: string
  lessonId: string
  exercise: CuratedExercise
}

/** Pick the first curated exercise in a lesson as the prompt base. */
function pickBaseInstance(
  lesson: Lesson,
): { id: string; instance: ExerciseInstance } | null {
  for (const ex of lesson.exercises) {
    if (ex.kind === 'curated') return { id: ex.id, instance: ex.instance }
  }
  return null
}

async function main() {
  if (!AUTH_TOKEN) {
    console.error('ANTHROPIC_AUTH_TOKEN is not set; aborting.')
    process.exit(2)
  }

  const targets: Array<{ topic: Topic; lesson: Lesson; baseId: string; baseInstance: ExerciseInstance }> = []
  for (const topic of TOPICS) {
    for (const lesson of topic.lessons) {
      // Treat both curated and param as valid intros — a param with
      // difficulty 'intro' is still an intro. The seed must add at most
      // one intro per lesson.
      const hasIntro = lesson.exercises.some((e) => e.difficulty === 'intro')
      if (hasIntro) continue
      const base = pickBaseInstance(lesson)
      if (!base) {
        // No curated base — the regenerate endpoint needs one. Skip; we'd
        // need a hand-authored intro here anyway.
        console.log(`[skip] ${topic.id}/${lesson.id}: no curated base exercise`)
        continue
      }
      targets.push({ topic, lesson, baseId: base.id, baseInstance: base.instance })
    }
  }

  console.log(`\n${targets.length} lessons need an intro. Generating…\n`)

  const seeds: SeedEntry[] = []
  const failures: Array<{ topicId: string; lessonId: string; reason: string }> = []
  let ok = 0
  let total = 0

  for (const t of targets) {
    total++
    process.stdout.write(`[${total}/${targets.length}] ${t.topic.id}/${t.lesson.id}… `)

    let result: { ok: true; instance: ExerciseInstance } | { ok: false; error: { kind: string } } | null =
      null

    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      result = await callRegenerate(
        {
          topic: t.topic,
          lesson: t.lesson,
          difficulty: 'intro' as Difficulty,
          original: t.baseInstance,
        },
        { baseUrl: BASE_URL, authToken: AUTH_TOKEN, model: MODEL },
      )
      if (result.ok) break
      process.stdout.write(`retry ${attempt}… `)
    }

    if (!result || !result.ok) {
      console.log('FAILED')
      failures.push({
        topicId: t.topic.id,
        lessonId: t.lesson.id,
        reason: !result ? 'no result' : JSON.stringify(result.error),
      })
      continue
    }
    console.log(`ok (${result.instance.answerType}, "${result.instance.answer.slice(0, 30)}")`)
    seeds.push({
      topicId: t.topic.id,
      lessonId: t.lesson.id,
      exercise: {
        kind: 'curated',
        id: `intro-${t.lesson.id}`,
        difficulty: 'intro',
        instance: result.instance,
      },
    })
    ok++
    // Brief pause to avoid hammering M3 / share server in self-host mode.
    await new Promise((r) => setTimeout(r, 250))
  }

  // Emit the sidecar module.
  const header = `/**
 * AUTO-GENERATED by scripts/seed-intros.ts. Do not edit by hand — re-run
 * the script to refresh. The merge in src/content/topics/index.ts reads
 * this map and prepends each entry to its lesson's exercises array.
 */

import type { CuratedExercise } from '../content/types'

export type LessonIntroMap = Record<string, Record<string, CuratedExercise>>
`
  const body = `export const LESSON_INTROS: LessonIntroMap = ${JSON.stringify(
    (() => {
      const out: Record<string, Record<string, CuratedExercise>> = {}
      for (const s of seeds) {
        if (!out[s.topicId]) out[s.topicId] = {}
        out[s.topicId][s.lessonId] = s.exercise
      }
      return out
    })(),
    null,
    2,
  )}
`
  await fs.writeFile(OUT, header + body)
  console.log(`\nWrote ${seeds.length} intros to ${path.relative(process.cwd(), OUT)}`)

  if (failures.length > 0) {
    console.log(`\nFailures (${failures.length}):`)
    for (const f of failures) console.log(`  ${f.topicId}/${f.lessonId}: ${f.reason}`)
  }

  log('seed-intros.done', { ok, total, failed: failures.length })
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
